let chara_data = [
    {"chara_id":1,"chara_name":"카야모리 루카","chara_short_name":"루카","troops":"31A","physical":1},
    {"chara_id":2,"chara_name":"이즈미 유키","chara_short_name":"유키","troops":"31A","physical":2},
    {"chara_id":3,"chara_name":"아이카와 메구미","chara_short_name":"메구미","troops":"31A","physical":3},
    {"chara_id":4,"chara_name":"토죠 츠카사","chara_short_name":"츠카사","troops":"31A","physical":2},
    {"chara_id":5,"chara_name":"아사쿠라 카렌","chara_short_name":"카렌","troops":"31A","physical":1},
    {"chara_id":6,"chara_name":"쿠니미 타마","chara_short_name":"타마","troops":"31A","physical":1},
    {"chara_id":7,"chara_name":"아오이 에리카","chara_short_name":"아오이","troops":"31B","physical":3},
    {"chara_id":8,"chara_name":"미나세 이치고","chara_short_name":"이치고","troops":"31B","physical":2},
    {"chara_id":9,"chara_name":"미나세 스모모","chara_short_name":"스모모","troops":"31B","physical":1},
    {"chara_id":10,"chara_name":"히구치 세이카","chara_short_name":"히구밍","troops":"31B","physical":2},
    {"chara_id":11,"chara_name":"히이라기 코즈에","chara_short_name":"코즈에","troops":"31B","physical":1},
    {"chara_id":12,"chara_name":"뱌코","chara_short_name":"뱌코","troops":"31B","physical":2},
    {"chara_id":13,"chara_name":"야마와키・본・이바르","chara_short_name":"야마와키","troops":"31C","physical":1},
    {"chara_id":14,"chara_name":"사쿠라바 세이라","chara_short_name":"세이라","troops":"31C","physical":3},
    {"chara_id":15,"chara_name":"텐네 미코","chara_short_name":"텐네","troops":"31C","physical":2},
    {"chara_id":16,"chara_name":"분고 야요이","chara_short_name":"분고","troops":"31C","physical":2},
    {"chara_id":17,"chara_name":"칸자키 아델하이드","chara_short_name":"아상","troops":"31C","physical":1},
    {"chara_id":18,"chara_name":"사츠키 마리","chara_short_name":"마리","troops":"31C","physical":2},
    {"chara_id":19,"chara_name":"니카이도 미사토","chara_short_name":"미사토","troops":"31D","physical":3},
    {"chara_id":20,"chara_name":"이시이 이로하","chara_short_name":"이로하","troops":"31D","physical":2},
    {"chara_id":21,"chara_name":"미코토 후부키","chara_short_name":"후부키","troops":"31D","physical":1},
    {"chara_id":22,"chara_name":"무로후시 리사","chara_short_name":"리사","troops":"31D","physical":2},
    {"chara_id":23,"chara_name":"다테 아카리","chara_short_name":"아카리","troops":"31D","physical":3},
    {"chara_id":24,"chara_name":"미즈하라 아이나","chara_short_name":"아이나","troops":"31D","physical":3},
    {"chara_id":25,"chara_name":"오오시마 이치코","chara_short_name":"이치코","troops":"31E","physical":3},
    {"chara_id":26,"chara_name":"오오시마 니이나","chara_short_name":"니이나","troops":"31E","physical":1},
    {"chara_id":27,"chara_name":"오오시마 미노리","chara_short_name":"미노리","troops":"31E","physical":3},
    {"chara_id":28,"chara_name":"오오시마 요츠하","chara_short_name":"요츠하","troops":"31E","physical":2},
    {"chara_id":29,"chara_name":"오오시마 이스즈","chara_short_name":"이스즈","troops":"31E","physical":1},
    {"chara_id":30,"chara_name":"오오시마 무우아","chara_short_name":"무우아","troops":"31E","physical":2},
    {"chara_id":31,"chara_name":"야나기 미온","chara_short_name":"야나기","troops":"31F","physical":2},
    {"chara_id":32,"chara_name":"마루야마 카나타","chara_short_name":"마루야마","troops":"31F","physical":2},
    {"chara_id":33,"chara_name":"하나무라 시키","chara_short_name":"시키","troops":"31F","physical":1},
    {"chara_id":34,"chara_name":"마츠오카 치로루","chara_short_name":"치로루","troops":"31F","physical":3},
    {"chara_id":35,"chara_name":"나츠메 이노리","chara_short_name":"이노리","troops":"31F","physical":1},
    {"chara_id":36,"chara_name":"쿠로사와 마키","chara_short_name":"마키","troops":"31F","physical":3},
    {"chara_id":37,"chara_name":"캐롤・리퍼","chara_short_name":"캐롤","troops":"31X","physical":1},
    {"chara_id":38,"chara_name":"리 잉시아","chara_short_name":"융융","troops":"31X","physical":1},
    {"chara_id":39,"chara_name":"아이린・레드메인","chara_short_name":"아이린","troops":"31X","physical":2},
    {"chara_id":40,"chara_name":"브리티카・발라크리시난","chara_short_name":"브리티카","troops":"31X","physical":3},
    {"chara_id":41,"chara_name":"마리아・데・안젤리스","chara_short_name":"마리아","troops":"31X","physical":3},
    {"chara_id":42,"chara_name":"샬로타・스코폽스카야","chara_short_name":"샤로","troops":"31X","physical":2},
    {"chara_id":43,"chara_name":"시라카와 유이나","chara_short_name":"유이나","troops":"30G","physical":1},
    {"chara_id":44,"chara_name":"츠키시로 모나카","chara_short_name":"모나카","troops":"30G","physical":3},
    {"chara_id":45,"chara_name":"키류 미야","chara_short_name":"미야","troops":"30G","physical":2},
    {"chara_id":46,"chara_name":"스가와라 치에","chara_short_name":"치에","troops":"30G","physical":3},
    {"chara_id":47,"chara_name":"오가사하라 히사메","chara_short_name":"히사메","troops":"30G","physical":2},
    {"chara_id":48,"chara_name":"쿠라 사토미","chara_short_name":"쿠라","troops":"30G","physical":1},
    {"chara_id":101,"chara_name":"나카무라 유리","chara_short_name":"유리","troops":"AB!","physical":1},
    {"chara_id":102,"chara_name":"타치바나 카나데","chara_short_name":"카나데","troops":"AB!","physical":2},
    {"chara_id":103,"chara_name":"이리에 미유키","chara_short_name":"미유키","troops":"AB!","physical":3},
    {"chara_id":104,"chara_name":"후치타 히사코","chara_short_name":"히사코","troops":"AB!","physical":3},
];
